# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

test_patterns = [
  "tests/**",
  "**/test_*.py"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
enabled = true
name = "test-coverage"
